import { Head, useForm } from '@inertiajs/react';
import { CertificatePlate } from '@/components/certificate-plate';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Design = { title: string; city: string; signatory: string; trainer_label: string; accent_color: string; border_style: 'single' | 'double' | 'modern'; shape: 'seal' | 'circle' | 'diamond'; logo_url?: string; background_url?: string; seal_url?: string; logo_path?: string; background_path?: string; seal_path?: string };

export default function CertificateBuilder({ design }: { design: Design }) {
    const { data, setData, put, processing, errors } = useForm({ ...design, logo: null as File | null, background: null as File | null, seal: null as File | null });
    return <div className="mx-auto flex w-full max-w-6xl flex-col gap-6 p-4"><Head title="Construtor de certificados" /><div><h1 className="text-2xl font-bold">Construtor de certificados</h1><p className="mt-1 text-muted-foreground">Configura textos, cores, formas, bordas e imagens do modelo.</p></div><div className="grid gap-6 lg:grid-cols-[380px_1fr]"><Card><CardContent className="flex flex-col gap-5 pt-6">{([['title', 'Título do certificado'], ['city', 'Cidade de emissão'], ['trainer_label', 'Assinatura do formador'], ['signatory', 'Assinatura institucional']] as const).map(([field, label]) => <div key={field}><Label htmlFor={field}>{label}</Label><Input id={field} className="mt-2" value={data[field]} onChange={event => setData(field, event.target.value)} /><p className="mt-1 text-xs text-destructive">{errors[field]}</p></div>)}<div><Label>Cor principal</Label><Input className="mt-2 h-10" type="color" value={data.accent_color} onChange={event => setData('accent_color', event.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><Label>Estilo de borda</Label><select className="mt-2 flex h-10 w-full rounded-md border bg-transparent px-3 text-sm" value={data.border_style} onChange={event => setData('border_style', event.target.value as Design['border_style'])}><option value="single">Simples</option><option value="double">Dupla</option><option value="modern">Moderna</option></select></div><div><Label>Forma do selo</Label><select className="mt-2 flex h-10 w-full rounded-md border bg-transparent px-3 text-sm" value={data.shape} onChange={event => setData('shape', event.target.value as Design['shape'])}><option value="seal">Selo</option><option value="circle">Círculo</option><option value="diamond">Losango</option></select></div></div>{([['logo', 'Logótipo'], ['background', 'Imagem de fundo'], ['seal', 'Selo personalizado']] as const).map(([field, label]) => <div key={field}><Label>{label}</Label><Input className="mt-2" type="file" accept="image/*" onChange={event => setData(field, event.target.files?.[0] ?? null)} /><p className="mt-1 text-xs text-destructive">{errors[field]}</p></div>)}<Button onClick={() => put('/admin/certificados/modelo')} disabled={processing}>Guardar modelo</Button></CardContent></Card><div><div className="mb-3 text-sm font-medium text-muted-foreground">Pré-visualização</div><CertificatePlate certificate={{ serial: 'MT-EXEMPLO-2026', student: 'Nome do formando', course: 'Nome do curso profissional', hours: 40, issued_at: '23 de setembro de 2026', design: { ...data, logo_url: design.logo_url, background_url: design.background_url, seal_url: design.seal_url } }} /></div></div></div>;
}

CertificateBuilder.layout = { breadcrumbs: [{ title: 'Certificados', href: '/admin/certificados' }, { title: 'Construtor', href: '/admin/certificados/modelo' }] };
